import { AppProvider } from "@/components/AppContext";
import Header from "@/components/layout/Header";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Footer from "../components/layout/Footer";
import { getServerSession } from "next-auth";
import { authOptions } from "../app/api/auth/[...nextauth]/route";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Food Cart",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = getServerSession(authOptions);
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
        <main className="container mx-auto pt-4">
          <AppProvider session={session}>
            <Toaster />
            <Header />
            <div className="min-h-screen">{children}</div>

            <Footer />
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
